### ISSUE TITLE
'NoneType' object has no attribute 'point_size'

### ISSUE THREAD

**Issue by nihao-eng** [ripl/nerfuser#4]
When I run python -m nerfuser.prep_data I get the following error. May I ask how to solve it? I am using the three videos you provided A, B, C, Test

Traceback (most recent call last):
  File "/home/zzu/anaconda3/envs/nerfuser/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zzu/anaconda3/envs/nerfuser/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zzu/w+1/nerfuser/nerfuser/prep_data.py", line 191, in <module>
    tyro.cli(main)
  File "/home/zzu/anaconda3/envs/nerfuser/lib/python3.10/site-packages/tyro/_cli.py", line 177, in cli
    output = _cli_impl(
  File "/home/zzu/anaconda3/envs/nerfuser/lib/python3.10/site-packages/tyro/_cli.py", line 430, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/zzu/anaconda3/envs/nerfuser/lib/python3.10/site-packages/tyro/_calling.py", line 204, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/home/zzu/w+1/nerfuser/nerfuser/prep_data.py", line 172, in main
    vis = Visualizer(show_frame=True)
  File "/home/zzu/w+1/nerfuser/nerfuser/utils/visualizer.py", line 17, in __init__
    self.o3d_vis.get_render_option().point_size = pt_size
AttributeError: 'NoneType' object has no attribute 'point_size'

**Comment by shengjie-lin** [comment]
try using open3d 0.16 instead of 0.17
`pip install open3d==0.16`

**Comment by nihao-eng** [comment]
> 

Thank you very much for your reply! I have solved this problem, but when I use the checkpoint you provided for fusion testing, a parameter mismatch error occurs:

`CUDA_VISIBLE_DEVICES=1 python -m nerfuser.fuser \
    --model-dirs TTIC-common/A/nerfacto/2023-05-21_014747/nerfstudio_models TTIC-common/B/nerfacto/2023-05-21_014753/nerfstudio_models TTIC-common/C/nerfacto/2023-05-21_014747/nerfstudio_models\
    --name my_scene \
    --model-names A B C \
    --model-gt-trans I \
    --cam-info ./dataset/test/transforms.json \
    --render-views \
    --run-sfm \
    --compute-trans \
    --test-poses ./dataset/test/transforms.json\
    --test-frame world \
    --blend-views \
    --eval-blend`


`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nerfuser/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/nerfuser/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/w+1/nerfuser/nerfuser/fuser.py", line 132, in <module>
    tyro.cli(Fuser).main()
  File "/home/ubuntu/w+1/nerfuser/nerfuser/fuser.py", line 101, in main
    ).main()
  File "/home/ubuntu/w+1/nerfuser/nerfuser/registration.py", line 167, in main
    ViewRenderer(self.model_method, self.model_names[i], self.model_dirs[i], load_step=self.step, chunk_size=self.chunk_size, device=self.device).render_views(poses_norm, cam_info, output_dir, animate=self.fps)
  File "/home/ubuntu/w+1/nerfuser/nerfuser/view_renderer.py", line 10, in __init__
    super().__init__(model_method, (model_name,), (load_dir,), transform[None], None, load_step=load_step, chunk_size=chunk_size, device=device)
  File "/home/ubuntu/w+1/nerfuser/nerfuser/view_blender.py", line 40, in __init__
    model.load_state_dict(state)
  File "/home/ubuntu/anaconda3/envs/nerfuser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NerfactoModel:
        Missing key(s) in state_dict: "field.direction_encoding.tcnn_encoding.params", "field.position_encoding.tcnn_encoding.params", "field.mlp_base_grid.hash_table", "field.mlp_base_grid.tcnn_encoding.params", "field.mlp_base_mlp.tcnn_encoding.params", "field.mlp_base.0.hash_table", "field.mlp_base.0.tcnn_encoding.params", "field.mlp_base.1.tcnn_encoding.params", "field.mlp_head.tcnn_encoding.params", "proposal_networks.0.encoding.hash_table", "proposal_networks.0.encoding.tcnn_encoding.params", "proposal_networks.0.mlp_base.0.hash_table", "proposal_networks.0.mlp_base.0.tcnn_encoding.params", "proposal_networks.0.mlp_base.1.tcnn_encoding.params", "proposal_networks.1.encoding.hash_table", "proposal_networks.1.encoding.tcnn_encoding.params", "proposal_networks.1.mlp_base.0.hash_table", "proposal_networks.1.mlp_base.0.tcnn_encoding.params", "proposal_networks.1.mlp_base.1.tcnn_encoding.params". 
        Unexpected key(s) in state_dict: "field.direction_encoding.params", "field.position_encoding.params", "field.mlp_base.params", "field.mlp_head.params", "proposal_networks.0.mlp_base.params", "proposal_networks.1.mlp_base.params".`

**Comment by nihao-eng** [comment]
> try using open3d 0.16 instead of 0.17 `pip install open3d==0.16`

Thank you very much for your reply! I have solved this problem, but when I use the checkpoint you provided for fusion testing, a parameter mismatch error occurs:

`CUDA_VISIBLE_DEVICES=1 python -m nerfuser.fuser \
    --model-dirs TTIC-common/A/nerfacto/2023-05-21_014747/nerfstudio_models TTIC-common/B/nerfacto/2023-05-21_014753/nerfstudio_models TTIC-common/C/nerfacto/2023-05-21_014747/nerfstudio_models\
    --name my_scene \
    --model-names A B C \
    --model-gt-trans I \
    --cam-info ./data/test/transforms.json \
    --render-views \
    --run-sfm \
    --compute-trans \
    --test-poses ./data/test/transforms.json\
    --test-frame world \
    --blend-views \
    --eval-blend`

> `Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nerfuser/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/nerfuser/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/w+1/nerfuser/nerfuser/registration.py", line 289, in <module>
    tyro.cli(Registration).main()
  File "/home/ubuntu/w+1/nerfuser/nerfuser/registration.py", line 167, in main
    ViewRenderer(self.model_method, self.model_names[i], self.model_dirs[i], load_step=self.step, chunk_size=self.chunk_size, device=self.device).render_views(poses_norm, cam_info, output_dir, animate=self.fps)
  File "/home/ubuntu/w+1/nerfuser/nerfuser/view_renderer.py", line 10, in __init__
    super().__init__(model_method, (model_name,), (load_dir,), transform[None], None, load_step=load_step, chunk_size=chunk_size, device=device)
  File "/home/ubuntu/w+1/nerfuser/nerfuser/view_blender.py", line 40, in __init__
    model.load_state_dict(state)
  File "/home/ubuntu/anaconda3/envs/nerfuser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NerfactoModel:
        Missing key(s) in state_dict: "field.direction_encoding.tcnn_encoding.params", "field.position_encoding.tcnn_encoding.params", "field.mlp_base_grid.hash_table", "field.mlp_base_grid.tcnn_encoding.params", "field.mlp_base_mlp.tcnn_encoding.params", "field.mlp_base.0.hash_table", "field.mlp_base.0.tcnn_encoding.params", "field.mlp_base.1.tcnn_encoding.params", "field.mlp_head.tcnn_encoding.params", "proposal_networks.0.encoding.hash_table", "proposal_networks.0.encoding.tcnn_encoding.params", "proposal_networks.0.mlp_base.0.hash_table", "proposal_networks.0.mlp_base.0.tcnn_encoding.params", "proposal_networks.0.mlp_base.1.tcnn_encoding.params", "proposal_networks.1.encoding.hash_table", "proposal_networks.1.encoding.tcnn_encoding.params", "proposal_networks.1.mlp_base.0.hash_table", "proposal_networks.1.mlp_base.0.tcnn_encoding.params", "proposal_networks.1.mlp_base.1.tcnn_encoding.params". 
        Unexpected key(s) in state_dict: "field.direction_encoding.params", "field.position_encoding.params", "field.mlp_base.params", "field.mlp_head.params", "proposal_networks.0.mlp_base.params", "proposal_networks.1.mlp_base.params".`

**Comment by shengjie-lin** [comment]
Maybe related [solution](https://stackoverflow.com/a/72200748).
